import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";

const prompt = Prompt({
  subsets: ["thai", "latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ['food', 'tracker', 'อาหาร', 'สุจภสฃาพ', 'health'],
  icons: {
    icon: '/vercel.svg'
  },
  authors: [{
    name: 'kakasupersavage',
    url: 'htpppornhub.org'
  }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt} ${prompt} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
